Hcb badges
andela/healthchecks_b pull request #1
Opened 2016-09-19 09:38 UTC by andela-kndegwa

2016-09-19 12:58 UTC, andela-calim commented on .gitignore
> +venv
Any reason why you're having two virtual environment folders in your application?

2016-09-19 13:01 UTC, iamlordaubrey requested changes
I wouldn't like to clutter the .gitignore file with multiple virtual env folders. We should all have one called `hc-venv` (as per the readme).

2016-09-19 13:12 UTC, andela-calim commented on README.md
> +[![PyPI](https://img.shields.io/pypi/pyversions/Django.svg?maxAge=2592000)]()
While you're it, I'm not sure the python badge is necessary. If you can defend it's necessity, by all means please do so. Else, let's remove it. LESS is MORE 😁

2016-09-19 16:56 UTC, andela-kndegwa commented on .gitignore
> +venv
Thats actually whitney who had **venv** as her virtual environment. I will let her know.

2016-09-19 16:57 UTC, andela-kndegwa commented on README.md
> +[![PyPI](https://img.shields.io/pypi/pyversions/Django.svg?maxAge=2592000)]()
Ok. Noted as well.

2016-09-19 18:05 UTC, andela-calim commented on .gitignore
> +hc_venv
virtual env should be hc-venv not hc_venv. Please take note... a hyphen, not an underscore.

2016-09-20 20:53 UTC, iamlordaubrey approved these changes

2016-09-20 20:53 UTC, merged