Hcb checksinterval
andela/healthchecks_b pull request #11
Opened 2016-10-03 13:26 UTC by kimobrian

I have worked on the feature to extend check periods and grace periods to a maximum of 5 years. Please review my chnages

2016-10-04 11:45 UTC, iamlordaubrey requested changes

2016-10-04 11:45 UTC, andela-calim commented on static/js/checks.js
> +            if($period_years==''){
For this, the if block is not performing any action. I think it is safe to say the code can be refactored. You can have an if block that checks if $period_years/months/weeks/days/hours/mins is not an empty string, and then perform the action you're currently performing in the else block.

2016-10-04 11:45 UTC, andela-calim commented on static/js/checks.js
> +            if($grace_years==''){
Review comment for $period_years applies here

2016-10-04 11:45 UTC, andela-calim commented on static/js/checks.js
> +    $('#period_months').bind('change keyup', function(){
Generally, when I see repeated code, I hear a voice whispering refactor. What comes to mind is all these stuff abstracted into a function that get's called and is passed a/some parameter(s).

2016-10-04 11:45 UTC, andela-calim commented on static/js/checks.js
> +    $('#grace_years').bind('change keyup', function(){
I hear the same refactor whisper

2016-10-04 11:45 UTC, andela-calim commented on static/js/checks.js
> +        // periodSlider.noUiSlider.set($this.data("timeout"))
Delete if not needed

2016-10-04 11:45 UTC, andela-calim commented on static/js/checks.js
> +        $("#update-timeout-form").submit(event, function() {
Not sure that this guy does. Delete if not needed

2016-10-04 12:37 UTC, kimobrian commented
I have made the requested changes, please review

2016-10-10 08:00 UTC, iamlordaubrey approved these changes

2016-10-10 08:00 UTC, merged