Hcb tests accounts
andela/healthchecks_b pull request #13
Opened 2016-10-04 08:29 UTC by andela-jmuli

2016-10-04 11:23 UTC, iamlordaubrey requested changes

2016-10-04 11:23 UTC, iamlordaubrey commented on hc/accounts/tests/test_login.py
> +        self.assertIsNotNone(User.objects.count(), 1)
Verify number of arguments assertIsNotNone() takes

2016-10-04 11:23 UTC, iamlordaubrey commented on hc/accounts/tests/test_login.py
>          ### Assert that check is associated with the new user
Remove these comments if not needed/fix if needed

2016-10-04 11:23 UTC, iamlordaubrey commented on hc/accounts/tests/test_switch_team.py
> +        # self.assertIsNotNone(r.content)
Delete if not needed

2016-10-04 11:23 UTC, andela-calim commented on hc/accounts/tests/test_team_access_middleware.py
> +        # profiles = Profile.objects.all(),count()
It seems what is expected is to assert Profile.objects.count equals 1 (since a new user was created.)

2016-10-13 16:18 UTC, andela-calim commented on hc/accounts/tests/test_login.py
> +        self.assertIsNotNone(User.objects.count(), 1)
Gentle reminder ^^^

2016-10-13 16:19 UTC, andela-calim commented on hc/accounts/tests/test_login.py
>          ### Assert that check is associated with the new user
Gentle reminder ^^^

2016-10-13 16:19 UTC, andela-calim commented on hc/accounts/tests/test_switch_team.py
> +        # self.assertIsNotNone(r.content)
Gentle reminder ^^^

2016-10-13 16:20 UTC, iamlordaubrey commented on hc/accounts/tests/test_team_access_middleware.py
> +        # profiles = Profile.objects.all(),count()
Gentle reminder ^^^

2016-10-13 16:59 UTC, andela-jmuli commented on hc/accounts/tests/test_login.py
> +        self.assertIsNotNone(User.objects.count(), 1)
noted

2016-10-14 12:38 UTC, iamlordaubrey approved these changes

2016-10-14 13:54 UTC, merged