Hcb docs
andela/healthchecks_b pull request #15
Opened 2016-10-10 09:37 UTC by kimobrian

Please review my changes. They don't do a lot of code refactoring but add major changes to the interface. I thought about videos but then decided to create an FAQs that cover almost everything so videos would be unnecessary. And with a live chat, a user can seek more clarification.

2016-10-12 08:05 UTC, andela-calim commented
Seems this guy has some conflicts. Please resolve

2016-10-12 08:06 UTC, iamlordaubrey requested changes
Please resolve merge conflicts

2016-10-12 09:54 UTC, kimobrian commented
I resolved the merge conflict

2016-10-13 15:00 UTC, iamlordaubrey approved these changes

2016-10-13 15:01 UTC, merged